from . import assessments
from . import res_partner
from . import slide_slide
from . import comments
from . import clients
from . import childs
from . import res_config_settings
from . import child_group
from . import parents
from . import ir_attachment
from . import res_users
