# -*- coding: utf-8 -*-

{
    'name': 'iwesabe Website Theme',
    'version': '15.0.0.1',
    'summary': 'Theme',
    'description': 'Theme',
    'license': "AGPL-3",
    'depends': ['auth_signup', 'portal', 'website', 'website_sale', 'website_sale_wishlist', 'website_blog', 'website_sale_stock',
                'compatibility_custom', 'purchase', 'project', 'hr_timesheet', 'web_domain_field', 'product', 'mass_mailing', 'mrp',
                'odoo_shipping_service_apps', 'payfort_payment_gateway'],
    'data': [
        # Data
        'security/ir.model.access.csv',
        'data/website_data.xml',
        # Website
        'templates/our_partner_template.xml',
        'templates/login_popup.xml',
        # 'templates/quick_view_modal.xml',
        'templates/header.xml',
        'templates/index.xml',
        'templates/gaming_pc.xml',
        'templates/cart1.xml',
        'templates/gear_store.xml',
        'templates/gear_store_type.xml',

        # old
        'templates/infiniarc_slider.xml',
        'templates/product_customize.xml',

        # 'templates/infiniarc_custom_checkout.xml',
        'templates/checkout.xml',
        'templates/payment_extend.xml',
        'templates/cart_summary.xml',
        'templates/shop.xml',
        'templates/infiniarc_support.xml',
        'templates/infiniarc_faq.xml',
        'templates/infiniarc_download.xml',
        'templates/infiniarc_orded_status.xml',
        'templates/infiniarc_aboutus.xml',
        'templates/infiniarc_warranty.xml',
        'templates/infiniarc_terms.xml',
        'templates/contactus_thankyou.xml',
        'templates/nvidia.xml',
        'templates/infiniarc_contactus.xml',
        'templates/infiniarc_quick_view_container.xml',
        'templates/product_details.xml',
        'templates/old_pages/product_filter.xml',
        'templates/special_offer.xml',
        'templates/login_page.xml',
        'templates/otp_login.xml',
        'templates/login_phone.xml',
        'templates/order_history_status.xml',
        'templates/my_portal.xml',
        'templates/checkout.xml',
        'templates/wishlist.xml',
        'templates/policy.xml',

        # Wizard
        'wizard/component_add_remove.xml',
        # Views
        'views/website_configuration_view.xml',
        'views/cpu_type.xml',
        'views/memories_type.xml',
        'views/component_type.xml',
        'views/brand_brand.xml',
        'views/add_pc_builder.xml',
        'views/our_partner_view.xml',
        'views/product_product.xml',
        'views/dynamic_micro_store.xml',
        'views/product_category.xml',
        'views/specification_item.xml',
        'views/radiator_size_values.xml',
        'views/infiniarc_faq.xml',
        'views/login_page.xml',
        'views/product.xml',
        'views/featured_product.xml',
        'views/infiniarc_custom_new_checkout.xml',
        'views/company_outlet_views.xml',
        'views/filters.xml',
        'views/banner.xml',
        'views/payfort_response_error.xml',
        'views/payfort_response_view.xml',
        'views/bank_details_views.xml',
        'views/transfer_response.xml',
        'views/infiniarc_response.xml',
    ],
    'installable': True,
    'auto_install': False,
    'category': 'Website',
    'assets': {
        'web.assets_frontend': [
            # CSS lib
            # 'iwesabe_website_theme/static/lib/css/slick.css',
            'iwesabe_website_theme/static/src/css/slick-theme.css',
            'iwesabe_website_theme/static/src/css/header.css',
            'iwesabe_website_theme/static/src/css/footer.css',
            'iwesabe_website_theme/static/src/css/homepage.css',
            'iwesabe_website_theme/static/src/css/homepage12.css',
            'iwesabe_website_theme/static/src/css/homepages.css',
            'iwesabe_website_theme/static/src/css/slider.css',
            'iwesabe_website_theme/static/src/css/desktop.css',
            'iwesabe_website_theme/static/src/css/style.css',
            'iwesabe_website_theme/static/src/css/style1.css',
            # 'iwesabe_website_theme/static/src/css/quick_view.css',
            'iwesabe_website_theme/static/src/css/style.min.css',
            'iwesabe_website_theme/static/src/css/product-card.css',

            'iwesabe_website_theme/static/src/css/game_pc.css',
            'iwesabe_website_theme/static/src/css/cart.css',
            'iwesabe_website_theme/static/src/css/checkout.css',
            'iwesabe_website_theme/static/src/css/categories.css',
            'iwesabe_website_theme/static/src/css/shop.css',
            'iwesabe_website_theme/static/src/css/megamenu.css',
            'iwesabe_website_theme/static/src/css/support.css',
            'iwesabe_website_theme/static/src/css/support1.css',
            'iwesabe_website_theme/static/src/css/quick_view_modal.css',
            'iwesabe_website_theme/static/src/css/new_homepage.css',
            'iwesabe_website_theme/static/src/css/gear_store_type.css',
            'iwesabe_website_theme/static/src/css/store.css',
            'iwesabe_website_theme/static/src/css/owl.carousel.css',
            'iwesabe_website_theme/static/src/css/owl.carousel.min.css',
            'iwesabe_website_theme/static/src/css/responsive.css',
            'iwesabe_website_theme/static/src/css/plus-jakarta.css',
            'iwesabe_website_theme/static/src/css/checkout_style.css',
            'iwesabe_website_theme/static/src/css/secondary-tile.css',
            # 'https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap',
            # 'https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;700&display=swap',
            'iwesabe_website_theme/static/src/css/product_customize.css',
            'iwesabe_website_theme/static/src/css/product_customize_bar_mob.css',
            'iwesabe_website_theme/static/src/css/product_customize_top_bar.css',
            'iwesabe_website_theme/static/src/css/trusted.css',
            'iwesabe_website_theme/static/src/js/product_customize.js',
            'iwesabe_website_theme/static/src/css/listpage.css',
            'iwesabe_website_theme/static/src/css/transfer_response.css',
            'iwesabe_website_theme/static/src/css/dashboard.css',
            'iwesabe_website_theme/static/src/css/banner.css',
            'https://fonts.googleapis.com/css2?family=Fira+Sans:wght@400;500&display=swap',
            'iwesabe_website_theme/static/src/css/fira-sans.css',
            'iwesabe_website_theme/static/src/css/hamburgers.min.css',
            'iwesabe_website_theme/static/src/css/filter_gst.css',
            'iwesabe_website_theme/static/src/css/product.css',
            'iwesabe_website_theme/static/src/css/buttons.css',
            'iwesabe_website_theme/static/src/css/newsletter.css',
            'iwesabe_website_theme/static/src/css/microdynamic.css',
            'iwesabe_website_theme/static/src/css/slick.css',
            'iwesabe_website_theme/static/src/css/fix.css',
            'iwesabe_website_theme/static/src/css/rdddeset.css',
            'iwesabe_website_theme/static/src/css/reset.css',

            # 'https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css',
            # 'https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css',

            # JS lib
            # 'iwesabe_website_theme/static/lib/js/slick.min.js',
            'iwesabe_website_theme/static/src/js/slick.min.js',
            'iwesabe_website_theme/static/src/js/custom.js',
            'iwesabe_website_theme/static/src/js/component.js',
            'iwesabe_website_theme/static/src/js/game_pc.js',
            'iwesabe_website_theme/static/src/js/gaming_desktop.js',
            'iwesabe_website_theme/static/src/js/megamenu.js',
            'iwesabe_website_theme/static/src/js/quick-view-js.js',
            'iwesabe_website_theme/static/src/js/infniarc_scroll.js',
            'iwesabe_website_theme/static/src/js/owl.carousel.min.js',
            'iwesabe_website_theme/static/src/js/cart.js',
            'iwesabe_website_theme/static/src/js/gearstore.js',
            'iwesabe_website_theme/static/src/js/microdynamic.js',
            'iwesabe_website_theme/static/src/js/product_customize.js',
            'iwesabe_website_theme/static/src/js/checkout.js',
            'iwesabe_website_theme/static/src/js/active_class.js',
            'iwesabe_website_theme/static/src/js/place_order.js',
            'iwesabe_website_theme/static/src/js/delivery_form.js',
            'iwesabe_website_theme/static/src/js/discount.js',

            'iwesabe_website_theme/static/src/js/login.js',
            'iwesabe_website_theme/static/src/js/newsletter.js',
            'iwesabe_website_theme/static/src/js/sort_drop.js',
            'iwesabe_website_theme/static/src/js/fly_to_cart.js',
            'iwesabe_website_theme/static/src/js/add_to_wishlist_icon.js',
            'iwesabe_website_theme/static/src/js/popup_add_to_cart.js',
            'iwesabe_website_theme/static/src/js/cart_quantity.js',
            # 'https://code.jquery.com/jquery-3.5.1.slim.min.js',
            # 'https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js',
            # 'https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js',

        ]
    }
}
