# -*- coding: utf-8 -*-

{
    'name': "Paceflow",
    'version': "15.0.1.0.0",
    'summary': """ Paceflow """,
    'description': """ Paceflow """,
    'author': "Ljutzkanov Ltd",
    'company': "Ljutzkanov Ltd",
    'maintainer': "Ljutzkanov Ltd",
    'website': "https://www.ljutzkanov.ltd/",
    'category': 'Tools',
    'depends': ['base', 'mail', 'contacts', 'sale', 'sale_management',  'web',
                'portal', 'website', 'website_slides'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/settings_template.xml',
        'data/data.xml',
        'data/email_template.xml',
        'data/paceflow_header.xml',
        'data/paceflow_footer.xml',
        'views/assessments_views.xml',
        'views/slide_slide_views.xml',
        'views/child_views.xml',
        'views/child_group.xml',
        'views/clients_views.xml',
        'views/comment_views.xml',
        'views/res_partner_views.xml',
        'views/res_config_settings_views.xml',
        'views/menuitems.xml',
        # 'views/assets.xml',
        'views/portal_templates.xml',
        'views/portal_child_list_template.xml',
        'views/client_dashboard_templates.xml',
        'views/historical_dashboard_templates.xml',
        'views/group_templates.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'paceflow/static/src/scss/colour_widget.scss',
            'paceflow/static/src/js/colour_widget.js',
            'paceflow/static/src/js/datepicker-full.min.js',
            'paceflow/static/src/js/video_preview.js',
            'paceflow/static/src/css/video_preview.css'
        ],
        'web.assets_frontend': [
            'https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js',
            'paceflow/static/src/css/dashboard.css',
            'paceflow/static/src/css/style.min.css',
            'paceflow/static/src/css/lib/nv.d3.css',
            'paceflow/static/src/css/lib/material-gauge.css',
            'paceflow/static/src/css/lib/video-js.css',
            # 'https://code.jquery.com/jquery-3.6.0.min.js',
            'https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js',
            'https://vjs.zencdn.net/7.17.0/video.min.js',
            'paceflow/static/src/js/upload_video.js',
            'paceflow/static/src/js/client_dashboard.js',
            'paceflow/static/src/js/history_dashboard.js',
            'paceflow/static/src/js/lib/FlexGauge.js',
            'paceflow/static/src/js/lib/d3.min.js',
            'paceflow/static/src/js/lib/Chart.bundle.js',
            'paceflow/static/src/js/lib/Chart.bundle.min.js',
            'paceflow/static/src/js/lib/Chart.min.js',
            'paceflow/static/src/js/lib/Chart.js'
        ],
        'web.assets_qweb': [
            'paceflow/static/src/xml/video_preview.xml',
        ],
    },
    'images': [],
    'license': "AGPL-3",
    'installable': True,
    'application': True
}
